// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pimvcujpkkndxjzhotwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpbXZjdWpwa2tuZHhqemhvdHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjM1MzMsImV4cCI6MjA2NTM5OTUzM30.w1l_oggEx6qdY9l9-jCZEW6tCcArFTffbohZj0bKPKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);